# Generated by Django 4.2.16 on 2024-11-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiverriss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='seguidores',
        ),
        migrations.AddField(
            model_name='usuario',
            name='siguiendo',
            field=models.ManyToManyField(blank=True, related_name='seguidores', to='apiverriss.usuario'),
        ),
    ]
